version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: type-coverage
    versions:
    - 2.17.4
  - dependency-name: tslint-react
    versions:
    - 5.0.0
  - dependency-name: webpack
    versions:
    - 5.28.0
    - 5.35.0
    - 5.35.1
    - 5.36.0
    - 5.36.1
  - dependency-name: gatsby-plugin-typescript
    versions:
    - 3.3.0
    - 3.4.0
  - dependency-name: gatsby-plugin-manifest
    versions:
    - 3.4.0
  - dependency-name: gatsby
    versions:
    - 3.3.1
    - 3.4.0
  - dependency-name: gatsby-image
    versions:
    - 3.4.0
  - dependency-name: gatsby-transformer-json
    versions:
    - 3.2.0
    - 3.3.0
    - 3.4.0
  - dependency-name: gatsby-transformer-sharp
    versions:
    - 3.2.0
    - 3.4.0
  - dependency-name: gatsby-plugin-offline
    versions:
    - 4.4.0
  - dependency-name: gatsby-plugin-sharp
    versions:
    - 3.4.0
  - dependency-name: gatsby-source-filesystem
    versions:
    - 3.4.0
  - dependency-name: gatsby-transformer-remark
    versions:
    - 4.0.0
    - 4.1.0
  - dependency-name: ssri
    versions:
    - 8.0.1
  - dependency-name: eslint-config-prettier
    versions:
    - 8.3.0
  - dependency-name: eslint-webpack-plugin
    versions:
    - 2.5.4
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.21.0
    - 4.22.0
  - dependency-name: eslint
    versions:
    - 7.23.0
    - 7.24.0
  - dependency-name: typescript
    versions:
    - 4.2.4
  - dependency-name: eslint-plugin-react
    versions:
    - 7.23.1
  - dependency-name: react-dom
    versions:
    - 17.0.2
  - dependency-name: react
    versions:
    - 17.0.2
